@startuml
!define MODEL_COLOR #0055CC
!define BACKGROUND_COLOR #D0E4FF

skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor BACKGROUND_COLOR

Package Model as ModelPackage <<Rectangle>> {
    Class "<<interface>>\nReadOnlyProfPlan" as ReadOnlyProfPlan
    Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
    Class "<<interface>>\nModel" as Model
    Class ProfPlan
    Class ModelManager
    Class UserPrefs

    Class UniqueTaskList
    Class Task {
        - Name name
        - Priority priority
        - RecurringType recurringType
        - Link link
        - Status status
        - DueDate dueDate
        - Description description
    }

    Class Name
    Class Priority
    Class RecurringType
    Class Link
    Class Status
    Class DueDate
    Class Description
    Class Tag
}


ReadOnlyProfPlan <|.. ProfPlan
Model <|.. ModelManager
ReadOnlyUserPrefs <|.. UserPrefs

ModelManager -left-> "1" ProfPlan
ModelManager -right-> "1" UserPrefs
ModelManager --> "~* filtered" Task

ProfPlan *--> "1" UniqueTaskList
UniqueTaskList --> "~* all  " Task

Task *-- Name
Task *-- Priority
Task *-- RecurringType
Task *-- Link
Task *-- Status
Task *-- DueDate
Task *-- Description
Task *-- "*" Tag

@enduml
