@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "ProfPlan Storage" #F4F6F6{
Class "<<interface>>\nProfPlanStorage" as ProfPlanStorage
Class JsonProfPlanStorage
Class JsonSerializableProfPlan
Class JsonAdaptedTask
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" ProfPlanStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> ProfPlanStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonProfPlanStorage .up.|> ProfPlanStorage
JsonProfPlanStorage ..> JsonSerializableProfPlan
JsonSerializableProfPlan --> "*" JsonAdaptedTask
JsonAdaptedTask --> "*" JsonAdaptedTag

@enduml
