@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ProfPlanParser" as ProfPlanParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedProfPlan" as VersionedProfPlan MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> ProfPlanParser : parseCommand(undo)
activate ProfPlanParser

create UndoCommand
ProfPlanParser -> UndoCommand
activate UndoCommand

UndoCommand --> ProfPlanParser
deactivate UndoCommand

ProfPlanParser --> LogicManager : u
deactivate ProfPlanParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoProfPlan()
activate Model

Model -> VersionedProfPlan : undo()
activate VersionedProfPlan

VersionedProfPlan -> VersionedProfPlan :resetData(ReadOnlyProfPlan)
VersionedProfPlan --> Model :
deactivate VersionedProfPlan

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
